ref: "/geode2/home/u040/justren/Quartz/fasta_ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
cram_base: "/N/scratch/cmguser/production/download"
bam_base: "/N/project/ICMH/Projects/6mA_COGA/filtered_reversed_bams"
pileup_base: "/N/project/ICMH/Projects/6mA_COGA/MODKIT_PILEUP_6mA"
manifest: "/N/slate/justren/shell_scripts/manifest837_570.csv"
modkit: "/N/slate/justren/modkit_dir/dist_modkit_v0.5.1_8fa79e3/modkit"
