#!/bin/bash
#SBATCH -J job_name
#SBATCH -p general
#SBATCH --cpus-per-task=10
#SBATCH --mem=90G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=user@email.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=4:00:00
#SBATCH -A -----
#SBATCH --array=10-13
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --error=logs/%x_%A_%a.err

mkdir -p logs

BARCODE=$SLURM_ARRAY_TASK_ID
SECTION="pod5_filerange"

dorado="/path/to/dorado/executable"
INPUT_DIR="/path/to/pod5_${SECTION}/bam_pass/barcode${BARCODE}"
BASE_OUTPUT_DIR="/path/to/output/pod5_${SECTION}/aligned"
REFERENCE="/path/to/reference/genome"

mkdir -p "$BASE_OUTPUT_DIR"

$dorado aligner -t $SLURM_CPUS_PER_TASK "$REFERENCE" "$INPUT_DIR" > "${BASE_OUTPUT_DIR}/barcode${BARCODE}_${SECTION}.bam
